### ISSUE TITLE
Game Logic 

### ISSUE THREAD

**Issue by retiv42** [MusicAdam/TotemDefender#14]
Win/Lose Condition
Phase management (Build/Battle)
With @kentb1

**Comment by MusicAdam** [comment]
(For the first prototype game will immediately load and enter game state)
GameState (@MusicAdam):
Entry Condition: Game is loaded
Exit condition: Totem is on the ground
onEnter: attach BuildState
update: Check if players are done building, if true attach BattleState
onExit: Detatch Battle state, set winner, attach PostGameState

PostGameState (@kentb1):
Entry condition: A player has won
Exit Condition: none (Wait for player to click done)
onEnter: Show PostGame menu 
update: none ?
onExit: attach GameState (create loop until we do main menu in protoype 2)
