### ISSUE TITLE
Libdx Implementation

### ISSUE THREAD

**Issue by retiv42** [MusicAdam/TotemDefender#2]

**Comment by MusicAdam** [comment]
Setup Libgdx with box2d to provide platform for team to develop.

Create class TotemDefender which extends the libgdx Application with following functions (In addition to the function defined in libgdx):
public boolean addEntity(Entity ent); //Adds an entity to the entity list if it has been spawned, returns true on success false on failure
public boolean destroyEntity(Entity ent); //Removes an entity from the entity list and the world as long as it exists, returns true on success false on failure
public Entity findEntity(int id); //Find an entity by id
public List<Entity> findEntityByName(String name); //Gets all entities with the given name
public List<Entity> getAllEntities(); //Gets all entities.
public World getWorld(); //Returns the box2d world.
public StateManager getStateManager(); //Gets the state manager

**Comment by MusicAdam** [comment]
See commit 
398703f8db

**Comment by MusicAdam** [comment]
Need to add asset manager

**Comment by MusicAdam** [comment]
e1ce66b060802131d60d3b63ff67bccb6e8d44f1
