### ISSUE TITLE
Blocks Hover in Thin Air Bug

### ISSUE THREAD

**Issue by alobaids** [MusicAdam/TotemDefender#38]
This bug can be seen if the player chooses to place extra blocks after placing the totem. Also, these blocks that are spawned after totem placement, canon balls go through these blocks. My suggestions:
1. Prevent the player from placing blocks after totem. 
2. Fix the bug. Possibly creating a sub building state and using the same code for spawning new blocks.

**Comment by MusicAdam** [comment]
Nice find!

This is a known issue and is a result of the build menu allowing users to proceed past the build state without "accepting" new blocks by pressing the select button (LSHIFT or RSHIFT depending on P1/P2 respectively). This is one of the tasks in my queue.

**Comment by MusicAdam** [comment]
This is actually a separate bug from the one I described. But it should get fixed with the build menu improvements.
