### ISSUE TITLE
Entity

### ISSUE THREAD

**Issue by retiv42** [MusicAdam/TotemDefender#4]
(Base world object)
Sprite
Physics Body

**Comment by MusicAdam** [comment]
An abstract class from which all game objects will derive.
Should have the following members:
public Entity(String name); //Constructor should accept a name to be used as a type identifier (all entities of the same type will have the same name, a unique int ID will be assigned on spawn)
public void update(); //Called by the main thread render loop if the entity is spawned, should have the entities sprite follow the box2d's body. Child classes should call super.update() upon override.
public abstract void render(); //Called by the main thread render loop
public abstract void spawn(); //Creates the box2d body, assigns the sprite, and adds the entity to the game's list of entities
public Vector2 getPosition(); //Returns the screen coordinates of the box2d body 
public void setPosition(Vector2 pos); //Sets the position of the box2d body (accepts screen coordinates, must convert from screen to world coords)
public Body getBody(); //Returns the box2d body 
public float getRotation(); //Returns the box2d body's rotation in radians
public void setRotation(float rot); //Sets the box2d body's rotation, accepts radians.
public void setSprite(Sprite sprite); //Sets the entities sprite.
public Sprite getSprite(); //Get sprite

**Comment by MusicAdam** [comment]
c68048fa7b050e5bf2d7d37efbd0d5f34f0cd42e
