### ISSUE TITLE
StateManager

### ISSUE THREAD

**Issue by retiv42** [MusicAdam/TotemDefender#5]
Encapsulate rendering and updates for entering and exiting different states.

**Comment by MusicAdam** [comment]
StateManager (Manages active states):
private List<State> activeStates; //List of states which affect the game
public void udpate(); //Calls active state's updates if entry condition is true, checks active states exit conditions, if the are met the state is updates and exited.
public void attachState(State state); //Attaches a state to the manager 
public void detachState(State state, boolean ignoreExitConidition); //Detaches a state, if ignoreExitCondition is true (default) the state will be detached regardless of its exit condition.

**Comment by MusicAdam** [comment]
State (Interface) provides a modular way to add behaviors to the game. The manager will call the state's update function if its entry condition is met, and detach it if its exit condition is met.
public boolean canEnter(); //Entry condition
public void onEnter(); //Called once upon entry
public void onExit(); //Called once upon exit
public boolean canExit(); //Exit condition
public void update(); //Called while the entry condition is true.

**Comment by MusicAdam** [comment]
See 398703f8db1ec9464c459438fe8c045758130bf9
